In [1]:
import numpy as np

1. Create a vector with values ranging from 10 to 49

In [2]:
x = np.arange(10, 50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Reverse a vector (first element becomes last)

In [3]:
np.flip(x)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [10]:
x[::-1]
np.array(sorted(x.tolist(), reverse=True))

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

3. Find indices of non-zero elements from [1,2,0,0,4,0]

In [17]:
x3 = np.array([1,2,0,0,4,0])
np.nonzero(x3)

(array([0, 1, 4]),)

In [21]:
y = x3 > 0
np.arange(x3.shape[0])[y]

array([0, 1, 4])

4. Create a 10x10 array with random values and find the minimum and maximum values 

In [26]:
a = np.random.rand(10, 10)
print(a.max())
print(a.min())

0.998333820021144
0.029637167775761752


In [28]:
a.shape

(10, 10)

5. Create a random vector of size 30 and find the mean value

In [33]:
np.random.rand(30).mean()

0.5239838122398937

In [34]:
np.array([np.random.uniform(0, 10*i, 10) for i in range(10)])

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 3.01521561,  9.14164803,  0.68791109,  2.89815842,  3.15728656,
         0.90899513,  9.86866755,  6.80097454,  0.84650805,  4.37712331],
       [ 8.39586685,  9.4721158 , 11.47671301,  9.98210744, 19.57495897,
        18.98315206, 10.96557931, 19.17685266,  2.34494457, 15.07271328],
       [10.63894158, 18.78178247,  2.11627782, 18.8364192 , 27.86439724,
        28.77513901,  3.00212305, 12.7432143 , 24.22477423,  5.126669  ],
       [ 8.01506109, 17.38200813, 16.83001306, 38.81288373, 27.20045135,
        36.48203461, 39.25869368,  6.1629328 , 33.86671744, 12.76535218],
       [12.58241805, 25.83004732, 42.08704151,  7.98036465, 30.59215561,
        47.90822083,  4.00450191, 17.97320344, 46.43838656, 37.61576568],
       [ 0.30392063, 34.98596739,  2.26471787, 39.25422566, 25.28928102,
        19.45190256, 19.43995083, 13.79122425

6. Create a 2d array with 1 on the border and 0 inside

In [46]:
bordermat = np.ones(shape=(10,10))
bordermat[1:-1, 1:-1] = 0
# bordermat[1:-1, 1:-1] = np.zeros(shape=(8, 8))
bordermat
# bordermat[0] = 1
# bordermat[-1] = 1
# bordermat[:, 0] = 1
# bordermat[:, -1] = 1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])